[package]
name = "segmented_vec"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "segmented_vs_vec"
harness = false
